spring.application.name=demo
# Configuracion de la Base de Datos
spring.datasource.url=jdbc:h2:mem:yogurtdb;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# CONFIGURACION DE JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

# CONFIGURACION DE H2 DE SU CONSOLA
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Ajustes para el login de hibernate 
logging.level.com.yougurtmaker=DEBUG
logging.level.org.hibernate.sql=DEBUG
logging.level.org.hibernate.type.descriptor.sql.basicBinder=TRACE

# Puerto de nuestra app
server.port=8082

# Inicializacion de SQL 
spring.sql.init.mode=always
